apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: pod-kill-example
  namespace: appns
spec:
  schedule: '*/1 * * * *'
  startingDeadlineSeconds: null
  concurrencyPolicy: Forbid
  historyLimit: 1
  type: PodChaos
  podChaos:
    selector:
      namespaces:
        - appns
    mode: one
    action: pod-kill
    gracePeriod: 0
